server:
  port: 8080

debug: true
logging:
  config: classpath:log4j2.yml

spring:
  application:
    name: onebox


  datasource:
    url: jdbc:mysql://192.168.134.251:3306/dnc?useUnicode=true&characterEncoding=UTF-8&useAffectedRows=true
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters:  stat,wall,slf4j
    # 合并多个DruidDataSource的监控数据
    useGlobalDataSourceStat: true
    #初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    #配置获取连接等待超时时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: false
    testOnBorrow: false
    testOnReturn: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: 20
    maxOpenPreparedStatements: 20

mybatis:
  #MyBatis相关自定义配置=
#  configLocation: classpath:mybatis.xml
  #mapper.xml所在位置
  mapper-locations: classpath:mapper/*.xml
  #实体包
  type-aliases-package: com.ob.model

#pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql

